### ISSUE TITLE
What lai de?

### ISSUE THREAD

**Issue by Jackmin801** [wing8169/iwill-experiment-fe#1]
Li go hai mat loi geh?
Zhe meh mou readme geh?

**Comment by Jackmin801** [comment]
Oh is it testing out nesting repos? ooooh

**Comment by wing8169** [comment]
Ima testing some libraries to do QR code scanning, PWA offline capabilities and other stuffs haha xD contributing? :3

**Comment by Jackmin801** [comment]
Nola. Too nub liao. Read ppls code only 🥺

**Comment by Jackmin801** [comment]
Question has been answered by very pro maintainer. Closing.
